name: Deploy Blog to Ionos

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # El usuario es tu nombre de GitHub (automático)
          username: ${{ github.actor }}
          # El password es un token temporal automático (no necesitas crearlo)
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Construir y Subir Imagen
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Cambia 'tu_usuario' por tu user real de Docker Hub
          tags: ghcr.io/${{ github.actor }}/blog-flask:latest

  deploy-to-vps:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar vía SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IONOS_HOST }}
          username: ${{ secrets.IONOS_USERNAME }}
          key: ${{ secrets.IONOS_SSH_KEY }}
          port: ${{ secrets.IONOS_SSH_PORT }}
          script: |
            # 1. Ir a la carpeta del proyecto (créala si no existe)
            # mkdir -p /srv/docker/blog-flask
            cd /srv/docker/blog-flask
            
            # 2. Crear el archivo .env actualizado con los secretos de GitHub
            # echo "${{ secrets.FLASK_ENV_PROD }}" > .env
            
            # 3. Descargar la última imagen
            docker pull ${{ secrets.DOCKER_USERNAME }}/mi-blog-flask:latest
            
            # 4. Reiniciar el contenedor (usando docker-compose)
            # Asegúrate de tener el docker-compose.yml en el servidor (ver paso 3)
            docker compose -f "blog.yml" up -d --force-recreate
            
            # 5. Limpiar imágenes viejas para ahorrar espacio
            docker image prune -f